import { tags } from "typia"

export interface IUserMinimal {
    uuid: string & tags.Format<"uuid">
    username: string & tags.MaxLength<255> & tags.Pattern<"^[a-zA-Z0-9_]+$">
}

export interface IUserFull extends IUserMinimal {
    "student-id": string & tags.MinLength<8> & tags.MaxLength<8>
    name: string & tags.MaxLength<255>
    class: number & tags.ExclusiveMaximum<100000> & tags.Minimum<0>
    year: number & tags.Type<"uint32">
    email: string & tags.MaxLength<255>
    "is-learner": boolean
    "is-tutor": boolean
}

type ValidateClass = tags.TagBase<{
    kind: "class"
    target: "number"
    value: undefined
    validate: `(() => {
        const year = new Date().getFullYear() % 100
        return Math.floor($input / 1000) === year
    })()`
}>

// create user verification, we want to be more restrictive on 'year' and 'class'
// 'uuid' is generated by the server
export interface ICreateUser
    extends Omit<IUserFull, "year" | "class" | "uuid"> {
    password: string & tags.MaxLength<255>
    year: number & tags.Minimum<1> & tags.Maximum<6>
    class: number & ValidateClass
}
